RSV2/foliage

- css/scss/apps/thirdchannel/_reports.scss
- js/apps/thirdchannel/views/reports/widgets/heatmap.js
https://thirdchannel.atlassian.net/browse/TC-1425
See companion PR on 3C side
> TC-1425 - Heat map view breakdowns

- js/apps/singleNickel/models/choice.js
- js/apps/singleNickel/models/question.js
- js/apps/singleNickel/models/section.js
- js/apps/singleNickel/templates/hbs-compiled.js
- js/apps/singleNickel/views/survey/build/builder.js
- templates/handlebars/singleNickel/survey/build/partials/show/_showQuestion.hbs
- templates/handlebars/singleNickel/survey/build/partials/show/_showSection.hbs
Related PR https://github.com/RSV2/SingleNickel/pull/2
> TC-1413 Ability to clone section and questions

- css/scss/apps/thirdchannel/_reports.scss
- js/apps/thirdchannel/views/reports/widgets/heatmap.js
- Removed unnecessary function calls
- Fixed issue where the axis' labels would change if resized.
- Fixed an issue with the legend being offcenter when in mobile.
- Reduced code to just a few standard calls.
> Optimized the heatmap class.

- css/scss/modules/_s3_uploader.scss
- js/apps/thirdchannel/templates/hbs-compiled.js
- templates/handlebars/thirdchannel/s3uploader/upload.hbs
Also see PR for thirdchannel app
> TC-1643 - fixing progress bar display on image upload

- js/apps/thirdchannel/views/legal/shipping.js
Code to handle the shipping address on the FTUE.
> TC-1560 - Adding dedicated shipping address

- js/apps/thirdchannel/routers/router.js
* Changes the path that triggers the shipping form validations during the FTUE process
See thirdchannel and supplication PRs
> TC-1663 ftue cleanup

- css/scss/modules/_site_filter.scss
- js/apps/bigTastysBackDoor/templates/hbs-compiled.js
- js/apps/pennyPacker/templates/hbs-compiled.js
- js/apps/procrastination/templates/hbs-compiled.js
- js/apps/thirdchannel/templates/hbs-compiled.js
- js/apps/thirdchannel/views/filter/component.js
- js/apps/thirdchannel/views/filter/filterControl.js
- js/apps/thirdchannel/views/filter/filterableComponent.js
- templates/handlebars/thirdchannel/filters/filterable_component.hbs
Adds the ability to filter down a filter list. Works around how the filter works (hide/show of active/inactive items).
> TC-1147 - Filterable filters

- js/apps/thirdchannel/views/labs/sc/side.js
https://thirdchannel.atlassian.net/browse/TC-1956
* Adds the average store associates spoken to to the appropriate section
* Add total number of store associates spoken to
Also see the thirdchannel PR
> TC-1956 - Moves average associates to the appropriate section

- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/templates/hbs-compiled.js
- js/apps/thirdchannel/views/profiles/stores/list.js
- templates/handlebars/thirdchannel/profiles/stores/rows.hbs
Front end for the profile store list (using the newer pagination scheme).
See PRs for supplication and thirdchannel.
> TC-1993 - displaying the agent's program profile store list

- js/apps/thirdchannel/views/reports/widgets/line_chart.js
- js/apps/thirdchannel/views/reports/widgets/metric_icon.js
https://thirdchannel.atlassian.net/browse/TC-1965
Added the ability to make a metric icon show "No Data" if it is in a given state
Added a config option for limiting the y tick
> tc-1965: changes to support new TOMS widgets

- js/apps/thirdchannel/views/checkins/show/survey.js
Hide or show the explain field based on whether trigger options are selected onchange.
https://thirdchannel.atlassian.net/browse/TC-2068
> tc-2068: show/hide explain field based on trigger

- css/scss/apps/thirdchannel/_reports.scss
- js/apps/thirdchannel/templates/hbs-compiled.js
- templates/handlebars/thirdchannel/reports/info/show/checkin.hbs
https://thirdchannel.atlassian.net/browse/TC-2000
* Updated how the data was being structured so it's a little easier to use in the view
* Added the task to be displayed above the answer (helpful for programs like luxottica where we can have multiple answers but it's impossible to know which survey (brand) they were in response to).
> TC-2000 - Updates to the Report Info Lists

- js/apps/thirdchannel/templates/hbs-compiled.js
- js/apps/thirdchannel/views/reports/widgets/range_chart.js
- templates/handlebars/thirdchannel/reports/widgets/range_chart.hbs
https://thirdchannel.atlassian.net/browse/TC-2347
> tc-2347: Add support for View Breakdown links to range chart

- js/apps/shared/views/layout/main.js
- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/views/reports/index/report.js
- js/apps/thirdchannel/views/reports/sync_report.js
- js/apps/thirdchannel/views/reports/widgets/generic_horizontal_bar_chart.js
- js/apps/thirdchannel/views/reports/widgets/heatmap.js
https://thirdchannel.atlassian.net/browse/TC-2712
https://github.com/RSV2/ThirdChannel/pull/193
> tc-2712: separate synchronous view for pdf reports

- js/apps/thirdchannel/templates/hbs-compiled.js
- templates/handlebars/thirdchannel/activities/sales_widget.hbs
https://thirdchannel.atlassian.net/browse/TC-2898
* Adding details link to all sales scenarios as a way to just see the data we have.
> TC-2898 - displaying the details link for all sales data scenarios

- css/scss/modules/stores/all.scss
- js/apps/bigTastysBackDoor/templates/hbs-compiled.js
- js/apps/oddjob/templates/hbs-compiled.js
- js/apps/pennyPacker/templates/hbs-compiled.js
- js/apps/shared/utils/handlebarsHelpers.js
- js/apps/stores/collections/account_similarities.js
- js/apps/stores/templates/hbs-compiled.js
- js/apps/stores/views/accounts/new.js
- js/apps/stores/views/accounts/similar_accounts.js
- templates/handlebars/stores/accounts/new.hbs
- templates/handlebars/stores/accounts/similar_accounts.hbs
https://thirdchannel.atlassian.net/browse/TC-2889
* Display a list of similar account during create
* If there is a direct match, it prevents the form from being submitted
* If there is a partial match, a confirmation dialog is displayed asking to verify that it really isn't already there
* Else it displays a confirm dialog to verify that they want to create the account
Also see PR for Store Service (on bitbucket).
> TC-2889 - adding account similarity list when creating an account

- css/scss/modules/_hoverable_image.scss
- js/apps/bigTastysBackDoor/templates/hbs-compiled.js
- js/apps/oddjob/templates/hbs-compiled.js
- js/apps/pennyPacker/templates/hbs-compiled.js
- js/apps/thirdchannel/templates/hbs-compiled.js
- js/apps/thirdchannel/views/shared/carousel.js
- js/apps/thirdchannel/views/shared/hoverable_image.js
- js/apps/thirdchannel/views/shared/infinite_scroll.js
- js/apps/thirdchannel/views/store_profile/gallery.js
- templates/handlebars/thirdchannel/hoverable_image.hbs
Swapped out on:
* full report page
* store profile page (most recent images)
* store image gallery
Also see PR for ThirdChannel
> TC-2169 - swapping the image modal with viewer w/ zoom capabilities

- js/apps/procrastination/templates/hbs-compiled.js
- js/apps/procrastination/views/schedule/current/list_visit.js
- templates/handlebars/procrastination/schedule/schedule_row.hbs
- templates/handlebars/procrastination/schedule/upcoming/visit.hbs
- templates/handlebars/procrastination/schedule/upcoming/visit_label.hbs
https://thirdchannel.atlassian.net/browse/TC-2572
> tc-2572: add job names to various UI elements

- js/apps/erudition/collections/opportunities.js
- js/apps/erudition/routers/router.js
- js/apps/erudition/templates/hbs-compiled.js
- js/apps/erudition/views/recruiting/opportunities.js
- js/apps/thirdchannel/templates/hbs-compiled.js
- templates/handlebars/erudition/recruiting/opportunities/_opportunity.hbs
- templates/handlebars/erudition/recruiting/opportunities/index.hbs
- templates/handlebars/erudition/recruiting/opportunities/list.hbs
Added a simple opportunities page that can be accessed by agents outside of the system
Part 3 of 3 (ThirdChannel, foliage, Erudition)
> Added page for the recruiters to get the opportunities urls

- js/apps/pennyPacker/routers/main.js
- js/apps/pennyPacker/views/entries/actions.js
- js/apps/thirdchannel/models/exports/sales_stores_audit.js
- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/views/exports/sales_stores_audit/main.js
https://thirdchannel.atlassian.net/browse/TC-3289
* Bootstraps the export modal for sales stores audit export.
Also, see PRs for thirdchannel and amalgamation
> TC-3289 - Sales stores visit audit

- js/apps/thirdchannel/models/exports/roi.js
- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/views/exports/roi/main.js
- js/apps/thirdchannel/views/exports/roi/roi.js
- js/apps/thirdchannel/views/labs/main.js
Changed the routes and the folders where the files are located to be consistent with our other export functionality.
> Moved ROI out of labs into exports

- css/scss/apps/oddjob/main.scss
- js/apps/oddjob/templates/hbs-compiled.js
- js/apps/oddjob/views/jobs/edit.js
- js/apps/oddjob/views/jobs/row.js
- js/apps/oddjob/views/tasks/list.js
- templates/handlebars/oddjob/jobs/_job_fields.hbs
- templates/handlebars/oddjob/jobs/row.hbs
https://thirdchannel.atlassian.net/browse/TC-3233
https://github.com/RSV2/oddjob/pull/7
> tc-3233: allowRescheduling view changes

- css/scss/apps/thirdchannel/_scheduled_visits.scss
- css/scss/apps/thirdchannel/main.scss
- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/templates/hbs-compiled.js
- js/apps/thirdchannel/views/scheduled_visits/scheduled_visit.js
- js/apps/thirdchannel/views/scheduled_visits/scheduled_visits.js
- templates/handlebars/thirdchannel/scheduled_visits/scheduled_visit.hbs
- templates/handlebars/thirdchannel/scheduled_visits/scheduled_visits.hbs
https://thirdchannel.atlassian.net/browse/TC-2750
> tc-2750: scheduled visits list

- js/apps/singleNickel/views/survey/list_item.js
- templates/handlebars/singleNickel/survey/list_item.hbs
Relates back to TC-3005: 
Fixed a bug where the clone toggles were only activating on the first survey regardless of which is activated (was an uncaught bug in my own code.. :( )
> Fixing toggle customer bug

- css/scss/modules/singleNickel/_survey.scss
- js/apps/singleNickel/init.js
- js/apps/singleNickel/modals/clone.js
- js/apps/singleNickel/views/survey/list_item.js
- templates/handlebars/singleNickel/modals/clone/clone.hbs
- templates/handlebars/singleNickel/survey/list.hbs
- templates/handlebars/singleNickel/survey/list_item.hbs
Moving the cloning UI buttons into a new modal. Also added some options that allow the user to navigate directly to the survey or to the new customer after successfully cloning.
> TC-4121 Moved clone logic into modal

- js/apps/shared/views/s3uploader/application_file.js
- js/apps/shared/views/s3uploader/checkin_file.js
- js/apps/shared/views/s3uploader/file.js
- templates/handlebars/shared/s3uploader/error.hbs
- Added size limit checks for file uploads (cannot be larger than 15 MB) and warnings when the user attempts to upload an image that is too large. 
- Cleaned up the alert logic so that one can specify an alert message to appear (instead of a default 'This may be caused be a bad internet connection!' message, which was showing up when the user for ex. tried to cancel their upload).
> TC-3423 Added size limit checks for file uploads

- js/apps/shared/utils/handlebarsHelpers.js
- js/apps/thirdchannel/views/comments/new_comment.js
https://thirdchannel.atlassian.net/browse/TC-4452 
https://thirdchannel.atlassian.net/browse/TC-4479
> add some leeway with spaces

- js/apps/shared/utils/handlebarsHelpers.js
https://thirdchannel.atlassian.net/browse/TC-4615
> add highlight support for two word display names

- css/scss/modules/_address_title.scss
small CS fixes; see linked PR on Thirdchannel
> TC-2299 CSS update for store status on store profile page

- css/scss/apps/thirdchannel/_activities.scss
- js/apps/thirdchannel/views/comments/new_comment.js
https://thirdchannel.atlassian.net/browse/TC-4659
> TC-4659: modify some of the autocomplete css to allow for wrapping on mobile

- js/apps/thirdchannel/views/comments/new_comment.js
https://thirdchannel.atlassian.net/browse/PS-691
> add null check

- js/apps/oddjob/templates/hbs-compiled.js
- js/apps/thirdchannel/views/fixtures/details/fixture.js
- js/apps/thirdchannel/views/fixtures/typesSummary.js
- templates/handlebars/thirdchannel/fixtures/fixture_detail_tile.hbs
https://thirdchannel.atlassian.net/browse/CQ-302
* Added the image viewer to the asset list details
* General tidiness
> CQ-302 - Adding image viewer to asset list report

- css/scss/apps/thirdchannel/_activities.scss
- js/apps/thirdchannel/registries/activities/store_sales.js
- js/apps/thirdchannel/views/activities/activity.js
- js/apps/thirdchannel/views/shared/sales_marquee.js
- js/apps/thirdchannel/views/stores/list.js
- templates/handlebars/thirdchannel/activities/sales_widget.hbs
- Now generated the sales URL internally so that it can always be present.
- Updated design for 'No Sales Data' state, and also link it to the sales page.
JIRA: https://thirdchannel.atlassian.net/browse/SD-287
Pairs with: https://github.com/RSV2/ThirdChannel/pull/477
> Updates to SalesMarquee

- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/views/store_profile/main.js
**What**
Add Store Intel route and make sure it inits ChoiceView.
**Why**
We added this page in the ThirdChannel repo and need to make sure we add the expandable card/choice viewer functionality. Pairs with https://github.com/RSV2/ThirdChannel/pull/481
**Jira:** https://thirdchannel.atlassian.net/browse/TC-5076
> Add store intel page to store profile

- css/scss/apps/thirdchannel/_activities.scss
- js/apps/thirdchannel/views/activities/activity.js
- js/apps/thirdchannel/views/comments/comment.js
- templates/handlebars/thirdchannel/activity.hbs
**What:** Design cleanup and slight restructuring of the bottom of posts on the activity feed. Requires https://github.com/RSV2/ThirdChannel/pull/484
**Why:** Some cleanup was desired/needed prior to incoming work for the hashtag system.
**Jira:** https://thirdchannel.atlassian.net/browse/TC-5100
**Before (desktop & mobile)**
**After (desktop & mobile)**
> Updates to activity feed post footer

- css/scss/apps/oddjob/main.scss
- templates/handlebars/oddjob/stores/list.hbs
- templates/handlebars/oddjob/stores/scheduled.hbs
1. I added labels two the store tables
1. I re-styled the tables to accommodate the new column, and to look more like the rest of our product.
1. I re-indented a scss file, because it had mixed (tabs and spaces) indents. The actual styling changes are in and around the ".store-row" section.
> TC-5084: show labels in stores tables, re-style tables, re-indent css

- js/apps/procrastination/routers/main.js
https://thirdchannel.atlassian.net/browse/TC-5199
This is intentionally a "quick and dirty" way of doing this.
> TC-5199: don't load the cost estimate views for vega agents

- js/apps/procrastination/views/schedule/upcoming/details_modal.js
- templates/handlebars/procrastination/schedule/upcoming/visit_label.hbs
> TC-5250 - adding products to details modal

- templates/handlebars/thirdchannel/scheduled_visits/scheduled_visit.hbs
- templates/handlebars/thirdchannel/scheduled_visits/scheduled_visits.hbs
https://thirdchannel.atlassian.net/browse/TC-5256
> TC-5256: do not display supervisor column if no supervisor role is set

- js/apps/erudition/views/profile/view_profile.js
- js/apps/thirdchannel/views/manage/jobs/main.js
- templates/handlebars/erudition/profile/view.hbs
https://thirdchannel.atlassian.net/browse/TC-5253
See PR for ThirdChannel (includes description of changes).
Also updated issue where a user was able to change the program store of a job request on update due to some irrelevant initial requirements.
> TC-5253 - adding additional fields for customer based users to view

- css/scss/apps/thirdchannel/main.scss
- js/apps/thirdchannel/init.js
- js/apps/thirdchannel/views/manage/jobs/create.js
- js/apps/thirdchannel/views/manage/jobs/main.js
- templates/handlebars/thirdchannel/manage/jobs/create.hbs
https://thirdchannel.atlassian.net/browse/TC-5289
* Adds new field to select assignee that is populated from users search api
* Populates the field on update with the current assignee
* Disables reassignment if the job request has been scheduled
Also see PR for ThirdChannel
> TC-5289 - Adding the ability to assign someone to a job request

- templates/handlebars/procrastination/schedule/upcoming/visit_label.hbs
https://thirdchannel.atlassian.net/browse/VEGA-53
> VEGA-53: show requestor info on modal on schedule edit page

- js/apps/thirdchannel/views/manage/jobs/create.js
- js/apps/thirdchannel/views/manage/jobs/dateRange.js
- js/apps/thirdchannel/views/manage/jobs/main.js
https://thirdchannel.atlassian.net/browse/VEGA-78
See PR for thirdchannel with description
> VEGA-78 - adding lead time for non-admins

- js/apps/thirdchannel/views/manage/jobs/create.js
https://thirdchannel.atlassian.net/browse/VEGA-57
> VEGA-57 - adding 15, 30, and 45 minute durations

- css/scss/apps/thirdchannel/_activities.scss
- js/apps/thirdchannel/views/checkins/list/store.js
- js/apps/thirdchannel/views/checkins/show/survey.js
- js/apps/thirdchannel/views/shared/sales_marquee.js
- templates/handlebars/thirdchannel/activities/sales_marquee.hbs
- templates/handlebars/thirdchannel/activities/sales_widget.hbs
- templates/handlebars/thirdchannel/checkins/list/store.hbs
**Why:** We want FMRs to be able to see stores sales data when completing their surveys.
**Jira:** https://thirdchannel.atlassian.net/browse/TC-5063
> [TC-5063] Add full-width mode to SalesMarquee, add to checkin workflow

- js/apps/thirdchannel/views/manage/jobs/create.js
- js/apps/thirdchannel/views/manage/jobs/main.js
- templates/handlebars/thirdchannel/manage/jobs/create.hbs
https://thirdchannel.atlassian.net/browse/VEGA-108
Also see PRs for ThirdChannel and Oddjob
> VEGA-108 - adding the ability for admins to change the requester of a job request

- css/scss/apps/thirdchannel/_field_activity.scss
- templates/handlebars/thirdchannel/reports/field_activity/kpis/generic_metric.hbs
https://thirdchannel.atlassian.net/browse/FAS-149
> FAS-149: add footnote to generic_metric template

- js/apps/thirdchannel/views/shared/sales_marquee.js
- templates/handlebars/thirdchannel/activities/sales_widget.hbs
The sales marque wont show when either previous years sales were 0 or store doesn't report sales $.
> SD-396 Marque won't show when there is no sales change

- js/apps/procrastination/views/schedule/upcoming/show.js
- templates/handlebars/procrastination/schedule/upcoming/visit.hbs
- templates/handlebars/thirdchannel/manage/jobs/assignment_history.hbs
https://thirdchannel.atlassian.net/browse/VEGA-132
This is just a sub-set of the overall feature for schedulable jobs that we want to release sooner
Also see PRs for ThirdChannel and Procrastination
> VEGA-132 - porting over sub-set of decline feature

- js/apps/thirdchannel/views/manage/jobs/create.js
- js/apps/thirdchannel/views/manage/jobs/main.js
https://thirdchannel.atlassian.net/browse/VEGA-143
Title explains it
Also see PR for ThirdChannel
> VEGA-143 - Adding the ability for admins/PMs to change assignee after a request has been scheduled

- css/scss/base/_buttons.scss
- templates/handlebars/thirdchannel/modals/confirmation.hbs
- Added styles to disable links
- Added additional message display for confirmation.
> Disable Delete visit for anyone other than admins

- js/apps/thirdchannel/models/exports/job_requests_coverage_export.js
- js/apps/thirdchannel/routers/router.js
- js/apps/thirdchannel/views/manage/jobs/coverageExport.js
https://thirdchannel.atlassian.net/browse/VEGA-182
Just wiring up the export for the coverage report.
Also see PR on ThirdChannel.
> VEGA-182 - adding the ability to create the coverage export
