RSV2/foliage

css/scss/layout/_base_layout.scss, css/scss/modules/_data_section.scss, js/apps/singleNickel/models/question.js, js/apps/singleNickel/templates/hbs-compiled.js, js/apps/thirdchannel/views/checkins/show/checkin.js, templates/handlebars/singleNickel/survey/show/partials/_QuestionSummary.hbs
This contains source code for about 3 tasks.
- First is the summary question on the survey builder.  Since this question type will be coming sometime soon, I don't think we need to worry about extracting it out, since we don't have any surveys we're building in the near future.
- Second is the fixes for a collapse and expand buttons on the reports.  Quick fix.
- Third is the optional images.  I've expanded the valid method to look for the existence of a required before and after image.  If they exist than they are checked for the usual things, otherwise we allow the user to enter an image if they want in either the before or after areas.
=> Optional images

js/apps/thirdchannel/views/reports/async_report.js
https://thirdchannel.atlassian.net/browse/TC-2648
The code that inserted widgets in their idx-dependent order was not always working right. I changed the way the async_report view works in order to make it consistent. Now, when the report_meta is render as the report skeleton, hidden placeholders are created for each widget. When each widget is rendered, the placeholder is swapped out for the actual widget view.
=> tc-2648: load widgets in order

js/apps/thirdchannel/views/reports/async_report.js, js/apps/thirdchannel/views/reports/index/report.js
https://thirdchannel.atlassian.net/browse/TC-2706
see also: https://github.com/RSV2/ThirdChannel/pull/192
When the filter was changing, the report was staying the same. Now when the filter changes, we should get a new report_meta before starting the async widget loading process.
=> tc-2706: load up a new report_meta when the filter changes

js/apps/thirdchannel/views/reports/index/report.js
https://thirdchannel.atlassian.net/browse/TC-2774
I forgot to include the case where the "report" param was left blank when loading a different report
=> tc-2774: if report param is not present, just get the default report

js/apps/singleNickel/models/survey.js, js/apps/singleNickel/views/survey/list_item.js, templates/handlebars/singleNickel/survey/list_item.hbs
Linked PR: SingleNickel TC-3005
UI update to allow users to clone surveys to different customers 
- added dropdown to allow users to pick the customer that the survey should clone to when attempting to clone a survey (defaults to current customer).
=> Allow user to clone surveys to different customers

js/apps/thirdchannel/views/labs/sales_comparison/side.js
https://thirdchannel.atlassian.net/browse/TC-4254
This removes a function that was adding an `onClick` action to the "View Breakdown" links in order to add a `customer_store_id` param. This was rewriting the `href`s incorrectly, which is why the links broke when opening the links normally. Opening them in a new tab worked fine because it did not trigger the `onClick`. @spember added the function originally, but was not sure what the `customer_store_id` param was used for. It does not seem to be used now, and it doesn't seem like it was ever used in `Reports::InfoController`. In all the cases I tried, it was being set to `null` anyway. The breakdowns appear to work fine without it.
=> TC-4254: remove function that was adding the discontinued customer_store_id param

js/apps/oddjob/templates/hbs-compiled.js, js/apps/thirdchannel/views/activities/activity.js, templates/handlebars/thirdchannel/activity.hbs, templates/handlebars/thirdchannel/task.hbs
Fixed an issue where we re-render the whole activity card every time we switch tasks (causing users to lose their comments while they are typing them).
We now instead only re-render the specific task details upon task switch.
**Changes**: created a taskRender() function which the initial render() calls as well as the loadTask() func. Split the activity template up into the task details (which should be re-rendered) and the rest of the activity card.
=> TC-2740 Rerendering only task details when switching tasks

js/apps/thirdchannel/views/activities/activities.js
**What:** Pulled in LoadingView into the activity feed, so that we can display it when we are waiting for filters to be applied on the feed.
**Why:** To provide better visual indicator that the system is still thinking or has finished.
**JIRA:** https://thirdchannel.atlassian.net/browse/PS-435
=> PS-435 Show loading indicator when waiting for filtered results

css/scss/apps/thirdchannel/_activities.scss, js/apps/shared/utils/handlebarsHelpers.js, templates/handlebars/thirdchannel/task.hbs
**What:** Only ever display a max of two line breaks between paragraphs in activity summaries.
**Why:** Some clients want particularly sectioned summaries from agent. We're already storing summaries with line breaks, so we only had to enable support for them. However, we want to make sure agents aren't abusing line breaks that would cause unnecessarily long entries in the activity feed. For checkins, we replace any instance 4+ line breaks with 3, which adds two lines of space between paragraphs.
**JIRA:** https://thirdchannel.atlassian.net/browse/PS-613
=> Trim excess new lines from activity summaries.

css/scss/apps/thirdchannel/_checkin.scss, js/apps/thirdchannel/views/checkins/expandable.js, js/apps/thirdchannel/views/checkins/in_progress.js, js/apps/thirdchannel/views/checkins/job.js, templates/handlebars/thirdchannel/checkins/activity.hbs, templates/handlebars/thirdchannel/checkins/expandable.hbs
https://thirdchannel.atlassian.net/browse/CQ-313
* Removed the icon from the submit report button
* Removed the expandable component from the page, should always be open
* Added "Visit Activities" header to page
* Removed the "View Recent Activities" from the visit activities page (shouldn't have been there, was inherited from the checkin expandable view).
Also see PR for thirdchannel.
=> CQ-313 - updates to the visit activities page

css/scss/apps/thirdchannel/_store_profile.scss, templates/handlebars/thirdchannel/store_profile/sales/chart_breakdowns.hbs, templates/handlebars/thirdchannel/store_profile/sales/overview.hbs
**What:** Modifying the styling on the store sales overview.
**Why:** To decrease repetition and to make things look more consistent across the page.
**Jira:** https://thirdchannel.atlassian.net/browse/TC-4851
**Before**
**After**
=> Updated styles on sales breakdown

templates/handlebars/thirdchannel/profiles/stores/rows.hbs
**What:** Add a new column to the table to display a link to the user's schedule for that store.
**Why:** How it was originally designed, and is easier to find.
**Jira:** https://thirdchannel.atlassian.net/browse/PS-626
=> Add column for schedule to Profile > Stores table

css/scss/apps/thirdchannel/_scheduled_visits.scss, templates/handlebars/thirdchannel/profiles/stores/rows.hbs
**Dependency:** https://github.com/RSV2/ThirdChannel/pull/439
**What:** Switched the Profile > Stores table layout to use the existing responsively-friendly version (as seen on the Stores listing).
**Why:** In adding an additional column to this table, the smaller screen layout was getting jumbled. This now displays in a more user-friendly way on smaller devices.
**Jira:** https://thirdchannel.atlassian.net/browse/PS-626
**Before**
**After**
=> Refactoring Profile > Stores table to use responsive collapsed table layout

css/scss/apps/thirdchannel/_activities.scss, js/apps/shared/utils/handlebarsHelpers.js, js/apps/thirdchannel/registries/activities/store_sales.js, js/apps/thirdchannel/views/activities/activity.js, templates/handlebars/thirdchannel/activities/sales_widget.hbs, templates/handlebars/thirdchannel/activity.hbs, templates/handlebars/thirdchannel/store_profile/sales/overview.hbs
**What:** Add a new display element to the sales widget that shows a store's latest sales data date, as well as amend copy on a store's report to show the latest sales data date.
**Why:** So users know the latest data we have available for the store.
**Jira:** https://thirdchannel.atlassian.net/browse/PS-602
**Through date display on Activity feed**
**Through date displayed as part of subheader on store report**
=> Display per-store sales data date on activity feed and on store reports

js/apps/thirdchannel/views/store_profile/sales/chart_breakdowns.js
**What:** Change how we calculate the height of the sales data graphs to be based on how many items are in the Y axis.
**Why:** These charts were set to a permanent 360px height. Wilson's data does not fit into this height so all the bars were overlapping. We now calculate the height of the chart by seeing if the data would display properly within the 360 limit. If not, we calculate what the minimum needed height is and use that value.
**Jira:** https://thirdchannel.atlassian.net/browse/SD-258
**Before**
**After**
=> [SD-258] Calculate sales chart height based on data

css/scss/apps/thirdchannel/_labs.scss
**What:** Hide the "View Breakdown" link that appears on chart widgets on the Labs page.
**Why:** The page this link brings you to is not really reflective of what the Labs page aims to illustrate, so it makes more sense to remove it.
**Jira:** https://thirdchannel.atlassian.net/browse/TC-4263
=> Hide widget "View Breakdown" links on Labs

js/apps/shared/utils/handlebarsHelpers.js
**What:** Change `formatDateToLongDate` to display the UTC time and not calculate the offset for the local timezone.
**Why:** It makes more sense for customers when looking at sales data.
**Jira:** https://thirdchannel.atlassian.net/browse/SD-278
=> Dont compensate for timezone when displaying sales data date

js/apps/thirdchannel/views/store_profile/sales/chart_breakdowns.js, js/apps/thirdchannel/views/store_profile/sales/report_layout.js
**What**
The labels of all the brands/categories are now Title Cased. This excludes the bold label in the graph below. 
** Why **
Wilson's Item Master has many different casings. We standardized them on the back end but they are in all caps. That looks ugly. 
Jira: https://thirdchannel.atlassian.net/browse/SD-260
=> SD-260 - Backend now has Upper Case Categories, so Title cased all the category labels

js/apps/thirdchannel/views/store_profile/sales/breakdown.js
**What:** Sort the sales breakdown chart alphabetically
**Why:** So it's easier to read through.
Within each brand, the categories are already sorted alphabetically, so we only have to sort the top level ourselves.
**Jira:** https://thirdchannel.atlassian.net/browse/SD-277
=> [SD-277] Sort sales breakdown table alphabetically

js/apps/thirdchannel/views/store_profile/sales/report_layout.js
**Dependency:** https://github.com/RSV2/ThirdChannel/pull/448
**What:** Look for a new key in the bootstrap payload, `view_sales_overview_breakdown`, to see if we should render this table.
**Why:** Given the nature of their data, Oakley and Wilson want to hide this table since it is redundant data and not very useful. Adding this new property allows us to hide this table for any program that has this property set in the `program_properties` table, a la sales data and labs access.
**Jira:** https://thirdchannel.atlassian.net/browse/SD-259
=> [SD-259] Add ability to hide sales overview breakdown table for programs

templates/handlebars/thirdchannel/store_profile/sales/breakdown.hbs, templates/handlebars/thirdchannel/store_profile/sales/chart_breakdowns.hbs
**What:** Always show "% Sales By Category" as the header for stores sales data breakdown.
**Why:** It's more flexible than "Brands" and makes enough sense for all clients at this point in time.
Also updated the table that displays below the chart for consistency.
**Jira:** https://thirdchannel.atlassian.net/browse/SD-276
=> Always show Sales By Category as store sales chart header

js/apps/shared/views/s3uploader/checkin_image.js, templates/handlebars/shared/s3uploader/checkin_image.hbs
https://thirdchannel.atlassian.net/browse/PS-706
A little tricky, the survey form itself is wrapped in a submit event (so pressing enter submits the form). Because of that it would also trigger the other buttons on the page.
To prevent the backbone views' confusion, changed the delete image buttons to links so they don't get triggered by submitting.
Also see PR for thirdchannel
=> PS-706 - preventing enter presses from deleting the image

js/apps/thirdchannel/views/checkins/task_list.js, templates/handlebars/thirdchannel/checkins/tasks.hbs
https://thirdchannel.atlassian.net/browse/TC-5074
The category select only dealt with normal tasks, needed to add support for activity packet based tasks.
Form required `packet_uuid` input and the action path is different.
=> TC-5074 - unable to start an optional activity packet task

css/scss/apps/thirdchannel/_activities.scss, css/scss/modules/_store_profile_section.scss, js/apps/thirdchannel/registries/activities/store_sales.js, js/apps/thirdchannel/views/activities/activity.js, js/apps/thirdchannel/views/shared/sales_marquee.js, js/apps/thirdchannel/views/stores/list.js, templates/handlebars/thirdchannel/activities/sales_marquee.hbs, templates/handlebars/thirdchannel/activities/sales_widget.hbs, templates/handlebars/thirdchannel/activity.hbs, templates/handlebars/thirdchannel/stores/rows.hbs
**What:** Introduces a new component, `SalesMarquee`, that will display $ Sales, Units OH, and Units Sold data on the activity feed as part of the activity. Some refactoring of the activity-meta area to allow for some visual changes.
**Jira:** https://thirdchannel.atlassian.net/browse/SD-287
=> Show Units OH and Units Sold as part of the $ Data on Activity Feed

js/apps/thirdchannel/views/manage/jobs/create.js
https://thirdchannel.atlassian.net/browse/TC-5305
Since the query now returns nil instead of empty array when no results are found, set the auto-complete results to an empty array.
=> TC-5305 - if no data is returned set the results as an empty array

js/apps/thirdchannel/views/reports/field_activity/overview.js, templates/handlebars/thirdchannel/reports/field_activity/overview.hbs
**What:** Update field activities to scroll to sections via JS rather than using IDs in anchor tags.
**Why:** When filters are applied to this page, attempting to scroll via the anchor ends up causing the filters to trigger an update and duplicate data rather than scrolling to the page. This method allows us to avoid that situation.
**Jira:** https://thirdchannel.atlassian.net/browse/FAS-107
=> [FAS-107]: Scroll to page sections with JS rather than traditional page anchors

js/apps/thirdchannel/views/filter/dateSlider.js, js/apps/thirdchannel/views/reports/field_activity/index/main.js, js/apps/thirdchannel/views/reports/field_activity/report.js
**What:** DateSlider now will update the start_date and end_date components in the page filters whenever a selection is updated.
**Why:** DateSlider is sort of a convenience interface for the date selection portion of the filters. It's not necessarily a 1:1 feature, which is was DateSlider doesn't extend from Filter, but it's actions affect what the Filters menu should do.
**Jira:** https://thirdchannel.atlassian.net/browse/FAS-113
=> [FAS-113] DateSlider component should properly update Filters component

js/apps/thirdchannel/views/filter/dateSlider.js, js/apps/thirdchannel/views/reports/field_activity/index/main.js
**What:** When the date slider initializes, check the page's current filters, and compare to the slider's current date mapping. If there's a match in ranges, set the slider position to that range, otherwise, default to the "Custom" option.
**Why:** When navigating back and forth between this page, the slider would also reset to 1 month, even if the filters were different in the URL. This also allows us to better deeplink this page so we can send URLs with particular dates filtered by default.
**Jira:** https://thirdchannel.atlassian.net/browse/FAS-105
=> [FAS-105] On initial load, match slider state to current filter state

js/apps/erudition/views/profile/edit.js, templates/handlebars/erudition/shared/_notifications.hbs
**What:** Removed the addition of the `chosen` variation of the email preferences dropdown when a user is editing their profile.
**Why:** It seems as though `jquery-validation` and `chosen` don't play nicely together. Since the rest of the inputs on this page aren't of the `chosen` variety, I took it out.
This now requires that a user sets their email preferences when editing their profile.
**Jira:** https://thirdchannel.atlassian.net/browse/TC-5390
=> [TC-5390 ] Require email opportunity preference selection when editing agent profile
